BC1-100-Build-Knowledge-Navigator-for-Blog
weprodev/BeeTheme pull request #114
Opened 2024-12-14 08:48 UTC by MaxRichard2007

2024-12-14 20:13 UTC, ahmadmohammadirad2006 requested changes

2024-12-14 20:13 UTC, ahmadmohammadirad2006 commented on blog/scss/layout/ـFeatured-Articles-Subscription.scss
> +.Blog__Highlights {
Based on the code convention we use hyphen-separated case for naming classes :)

2024-12-14 20:13 UTC, ahmadmohammadirad2006 commented on blog/scss/layout/ـFeatured-Articles-Subscription.scss
> +.Featured-Articles-Subscription {
Also this class like the previous one

2024-12-15 10:09 UTC, ahmadmohammadirad2006 approved these changes

2024-12-15 12:56 UTC, sadiGFG approved these changes

2024-12-15 12:58 UTC, merged