BC1-36-typography-for-solar-land
weprodev/BeeTheme pull request #18
Opened 2024-10-19 15:04 UTC by abdolmajed3

Applied the Quicksand font across the template for consistent styling.
    Updated SCSS variables to reflect new font integration and weights (300-700).

Please review and merge if all looks good.

2024-10-19 15:14 UTC, ahmadmohammadirad2006 requested changes

2024-10-20 09:35 UTC, abdolmajed3 commented on solar-land/scss/main.scss
> +
you right but the first line not describing about color. i added comment to tell about color that imported with this file.

2024-10-20 10:59 UTC, ahmadmohammadirad2006 approved these changes
Well done bro

2024-10-20 11:28 UTC, MichaelAndish requested changes

2024-10-20 11:28 UTC, MichaelAndish commented on solar-land/scss/_typography.scss
> +// Typography for Quicksand font
I think, because the file name is typography so it's clear it's for typography, right?, so this comment is not useful

2024-10-20 11:28 UTC, MichaelAndish commented on solar-land/scss/_typography.scss
> +  font-family: "Quicksand", sans-serif;
question, why you didn't use variable for primaryFontFamily?

2024-10-20 11:28 UTC, MichaelAndish commented on solar-land/scss/_typography.scss
> +  font-family: "Quicksand", sans-serif;
You repeated the font family in all of this file, it means it should be manageable by using variable

2024-10-20 11:28 UTC, MichaelAndish commented on solar-land/scss/_variables.scss
> +$primaryColor: #0dd47e; // Used for buttons, active states, and highlights.
when you call it Primary Color, it means for the all part of the project it'll use, you don't need to comment it

2024-10-20 11:28 UTC, MichaelAndish commented on solar-land/scss/_variables.scss
> +// defining colors
please use the comment structure that we have. 
you can just call it COLORS.
```
/*------------------------------------*\
  #COLORS
\*------------------------------------*/
```

2024-10-20 11:28 UTC, MichaelAndish commented on solar-land/scss/main.scss
> +@import "variables"; // import variables file that contains color and font import
I think the comment is not useful, everyone knows we define all those variables there. let's make code less and clean by removing redundant comments

2024-10-22 13:39 UTC, closed without merging