BC1–53-feat:Creating the initial structure of the project showland
weprodev/BeeTheme pull request #27
Opened 2024-10-24 14:26 UTC by sadiGFG

2024-10-28 14:17 UTC, ahmadmohammadirad2006 requested changes

2024-10-28 14:17 UTC, ahmadmohammadirad2006 commented on show-land/index.html
> +    </html>
Please use "prettier" to format the code as mentioned in code convention's page :)

2024-10-28 14:17 UTC, ahmadmohammadirad2006 commented on show-land/sass/_variables.scss
> +$colorIfth:#1864ab;
I think you meant 
```
$colorFifth: #1864ab;
```
So if it is a typo, fix it please

2024-10-28 14:17 UTC, ahmadmohammadirad2006 commented on show-land/index.html
> +</div>
Which tag does this </div> tag close?

2024-10-28 14:17 UTC, ahmadmohammadirad2006 commented on show-land/index.html
> +</div>
This one like the previous one does not have an opening tag.

2024-10-28 20:10 UTC, ahmadmohammadirad2006 commented on show-land/sass/main.scss
> +@import"../../shared/scss/base/reset";
Please separate the imports into logical parts like you have done for your variables file

2024-10-29 03:31 UTC, MaxRichard2007 requested changes

2024-10-29 14:10 UTC, ahmadmohammadirad2006 approved these changes

2024-10-29 20:48 UTC, MichaelAndish requested changes

2024-10-29 20:48 UTC, MichaelAndish commented on show-land/sass/_variables.scss
> +$colorWihte: #fff;
there is a typo, $colorWhite

2024-10-29 20:48 UTC, MichaelAndish commented on show-land/sass/main.scss
> +@import "components/button";
You imported shared button and your button! which one do you want to use?

2024-10-29 21:23 UTC, sadiGFG commented on show-land/sass/main.scss
> +@import "../../shared/scss/components/button";
Your opinion is respected, but for now it is better to be like this

2024-10-30 19:49 UTC, MichaelAndish approved these changes

2024-10-30 19:49 UTC, merged