Bc1 33 create a hero section be responsive for app land
weprodev/BeeTheme pull request #30
Opened 2024-10-25 12:48 UTC by MaxRichard2007

2024-10-31 06:52 UTC, sadiGFG commented on app-land/scss/layout/_heroSection.scss
> +      }
Please use rem or em if possible

2024-10-31 09:20 UTC, sadiGFG commented on app-land/scss/layout/_heroSection.scss
>    }
Why did you use px again here?

2024-10-31 09:20 UTC, sadiGFG commented on app-land/scss/layout/_heroSection.scss
> +      font-size: 10px;
Please fix this too

2024-11-04 14:47 UTC, ahmadmohammadirad2006 requested changes

2024-11-04 14:47 UTC, ahmadmohammadirad2006 commented on app-land/scss/component/_button.scss
> +    border-radius: 2rem;
You can use border radius variables from shared folder when you need border radius in your project  :)

2024-11-04 14:47 UTC, ahmadmohammadirad2006 commented on app-land/scss/layout/_heroSection.scss
> +        font-weight: 600;
Please use font weight variables from shared variables ;-)

2024-11-04 14:47 UTC, ahmadmohammadirad2006 commented on app-land/scss/layout/_heroSection.scss
> +        padding-top: 1rem;
For padding, margin and gap you can use $spaces list from shared variables :)

2024-11-04 14:47 UTC, ahmadmohammadirad2006 commented on app-land/scss/layout/_heroSection.scss
> +          font-size: 1rem;
Again here you can use font size variables from shared folder

2024-11-04 21:42 UTC, sadiGFG approved these changes

2024-11-07 17:25 UTC, ahmadmohammadirad2006 approved these changes
Good job bro

2024-11-07 17:27 UTC, merged