BC1-47-hero-section-for-solar-land
weprodev/BeeTheme pull request #43
Opened 2024-11-01 18:09 UTC by abdolmajed3

**Added hero section**
created a hero.scss file.
added a photo for hero section.
added hero html codes in the index.html file.
imported the hero.scss file in the main.scss file.

**added customers section**
added a example logo for the customers section

**changes on shared codes :**
- Added 2 new font size variables
$fontSize5Xl: 2.625em;
$fontSize6Xl: 3em;

- Added more border radius sizes
$rounded2Xl: 0.75em;
$rounded3Xl: 1em;
$rounded4Xl: 1.25em;

2024-11-02 16:01 UTC, ahmadmohammadirad2006 requested changes

2024-11-02 16:13 UTC, abdolmajed3 commented on solar-land/scss/layout/hero.scss
> +      }
i don't know why i forgot to mix that 👍

2024-11-02 16:14 UTC, abdolmajed3 commented on solar-land/scss/layout/hero.scss
> +      gap: 8px;
Oh this one ;)
thanks bro.

2024-11-02 17:43 UTC, ahmadmohammadirad2006 approved these changes
Great job

2024-11-07 16:51 UTC, MaxRichard2007 approved these changes

2024-11-07 17:16 UTC, merged