BC1-58-fix:fix search box on top bar and add js file for search box
weprodev/BeeTheme pull request #58
Opened 2024-11-09 21:34 UTC by sinaalimi

2024-11-10 12:09 UTC, MichaelAndish requested changes

2024-11-10 12:09 UTC, MichaelAndish commented on product-details/js/main.js
> +      // $(this).addClass("icon-close dbl-click");
if you don't use it, just remove the comments

2024-11-10 12:09 UTC, MichaelAndish commented on product-details/scss/layout/nav-bar.scss
> +            .Circle {
why it's capitalcase? `.Circle`

2024-11-10 12:09 UTC, MichaelAndish commented on product-details/scss/layout/top-bar.scss
> +  // color: $white;
if you don't use it, remove the comment

2024-11-10 12:09 UTC, MichaelAndish commented on product-details/scss/layout/top-bar.scss
> +            list-style: none;
why we have 2 types of mixin name? retinaMobile is camelCase and  mini_laptop is snake_case ?!

2024-11-10 12:09 UTC, MichaelAndish commented on product-details/scss/layout/top-bar.scss
> +
Maybe you can re-use the shared component?!

2024-11-11 05:43 UTC, abdolmajed3 commented on product-details/index.html
> +    function myFunction() {
i think its better to change function name.

>  Prefer descriptive variable and function names.

2024-11-11 05:43 UTC, abdolmajed3 commented on product-details/js/main.js
> +function myFunction() {
> - Prefer descriptive variable and function names.

2024-11-19 04:54 UTC, MichaelAndish commented
@sinaalimi you have icomoon in 2 places, why?! shared folder and inside the project

2024-11-21 21:14 UTC, merged