Bc1 69 responsive of the all project showland
weprodev/BeeTheme pull request #69
Opened 2024-11-16 17:34 UTC by sadiGFG

2024-11-23 15:56 UTC, ahmadmohammadirad2006 approved these changes

2024-11-23 17:24 UTC, abdolmajed3 requested changes

2024-11-23 17:24 UTC, abdolmajed3 commented on show-land/css/queries.css
> +@media (max-width: 87em) {
we have sizes for media queries in our shared variables. you can use that.

2024-11-23 17:24 UTC, abdolmajed3 commented on show-land/sass/layout/_super-fast.scss
> +      list.nth($spaces, 4);
you can only write this code :
`padding: list.nth($spaces, 1) list.nth($spaces, 4)`

2024-11-24 05:15 UTC, abdolmajed3 approved these changes

2024-11-24 10:20 UTC, merged