BC1-93-Build-Blog-Header
weprodev/BeeTheme pull request #93
Opened 2024-11-27 14:32 UTC by MaxRichard2007

2024-11-29 08:58 UTC, ahmadmohammadirad2006 requested changes

2024-11-29 08:58 UTC, ahmadmohammadirad2006 commented on blog/scss/_typography.scss
> +}
I think some of the styles are more related to base styles, so I think creating a new file like "_base.scss" in blog folder would be cleaner :)

2024-11-29 08:58 UTC, ahmadmohammadirad2006 commented on blog/scss/component/_button.scss
> +}
Please use the button component from shared folder, and also you can get padding, font-size, border-radius .. . values from shared variables too :)

2024-11-29 08:58 UTC, ahmadmohammadirad2006 commented on blog/scss/layout/_header.scss
> +        border-radius: 1.5625rem;
Can you get the value from shared variables ? :)

2024-11-29 17:27 UTC, ahmadmohammadirad2006 approved these changes

2024-12-05 08:23 UTC, sadiGFG approved these changes

2024-12-05 09:12 UTC, merged